<a href="https://colab.research.google.com/github/siddartharaj06/Python-For-Data-Science/blob/main/Lab_2_7th_aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Student Grades Analysis Using NumPy Arrays

import numpy as np

# Step 1: Create a 2D NumPy array for student marks in 3 subjects
# Rows → students, Columns → subjects
marks = np.array([
    [85, 78, 92],  # Student 1
    [56, 74, 60],  # Student 2
    [90, 88, 95],  # Student 3
    [70, 65, 72],  # Student 4
    [88, 92, 85]   # Student 5
])

print("Student Marks (Rows=Students, Cols=Subjects):\n", marks)

# Step 2: Calculate average, minimum, and maximum marks
average_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nOverall Average Marks:", average_marks)
print("Minimum Marks:", min_marks)
print("Maximum Marks:", max_marks)

# Step 3: Slicing → retrieve marks of specific students
# Example: Marks of student 2 and 4
print("\nMarks of Student 2:", marks[1])
print("Marks of Student 4:", marks[3])

# Step 4: Boolean indexing → find students scoring above 80 in any subject
above_80 = marks > 80
print("\nBoolean Mask (True = score > 80):\n", above_80)

# Students who scored >80 in at least one subject
students_above_80 = np.any(above_80, axis=1)
print("\nStudents scoring >80 in at least one subject:", np.where(students_above_80)[0] + 1)

# Step 5: Reshape the array → subject-wise performance
# Shape before: (5 students × 3 subjects)
# Shape after: (3 subjects × 5 students)
subject_wise = marks.T
print("\nSubject-wise Performance (Rows=Subjects, Cols=Students):\n", subject_wise)

# Step 6: Comment on observed results
print("\nObservation:")
print("- Subject 3 has the highest marks overall.")
print("- Students 1, 3, and 5 frequently score above 80.")
print("- Subject-wise view shows consistency of Student 3 across all subjects.")


Student Marks (Rows=Students, Cols=Subjects):
 [[85 78 92]
 [56 74 60]
 [90 88 95]
 [70 65 72]
 [88 92 85]]

Overall Average Marks: 79.33333333333333
Minimum Marks: 56
Maximum Marks: 95

Marks of Student 2: [56 74 60]
Marks of Student 4: [70 65 72]

Boolean Mask (True = score > 80):
 [[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

Students scoring >80 in at least one subject: [1 3 5]

Subject-wise Performance (Rows=Subjects, Cols=Students):
 [[85 56 90 70 88]
 [78 74 88 65 92]
 [92 60 95 72 85]]

Observation:
- Subject 3 has the highest marks overall.
- Students 1, 3, and 5 frequently score above 80.
- Subject-wise view shows consistency of Student 3 across all subjects.


In [2]:
# Employee Salary Analysis with pandas DataFrame

import pandas as pd

# Step 1: Create DataFrame from dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "ID": [101, 102, 103, 104, 105],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [48000, 55000, 72000, 50000, 65000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Step 2: Filter employees with salary > 50,000
high_salary_df = df[df["Salary"] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary_df)

# Step 3: Sort DataFrame by salary in descending order
sorted_df = df.sort_values(by="Salary", ascending=False)
print("\nDataFrame Sorted by Salary (Descending):\n", sorted_df)

# Step 4: Add a new column for Bonus (10% of salary)
df["Bonus"] = df["Salary"] * 0.10
print("\nDataFrame with Bonus Column:\n", df)

# Step 5: Calculate total salary expense including bonuses
total_expense = df["Salary"].sum() + df["Bonus"].sum()
print("\nTotal Salary Expense (Including Bonuses):", total_expense)

# Step 6: Save DataFrame to a CSV file
df.to_csv("employee_data.csv", index=False)
print("\nDataFrame saved to 'employee_data.csv'")


Original DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   48000
1      Bob  102         IT   55000
2  Charlie  103    Finance   72000
3    David  104         IT   50000
4      Eva  105  Marketing   65000

Employees with Salary > 50,000:
       Name   ID Department  Salary
1      Bob  102         IT   55000
2  Charlie  103    Finance   72000
4      Eva  105  Marketing   65000

DataFrame Sorted by Salary (Descending):
       Name   ID Department  Salary
2  Charlie  103    Finance   72000
4      Eva  105  Marketing   65000
1      Bob  102         IT   55000
3    David  104         IT   50000
0    Alice  101         HR   48000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   48000  4800.0
1      Bob  102         IT   55000  5500.0
2  Charlie  103    Finance   72000  7200.0
3    David  104         IT   50000  5000.0
4      Eva  105  Marketing   65000  6500.0

Total Salary Expense (Including Bonuses): 319000.0

